import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import InfiniteScroll from 'react-infinite-scroll-component';
import { Layout } from '../components/Layout';
import { MoviesGrid } from '../components/MoviesGrid';
import useResults from '../hooks/useResults';
import { Movie } from '../interfaces/Movie';
import { MovieList } from '../interfaces/MovieList';

const Home = ({ data }: { data: MovieList }) => {
  const { results, hasMore, fetchMoreResults } = useResults(data, 'movies');

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {results && <MoviesGrid data={data} api="movies" />}
    </Layout>
  );
};

export const getServerSideProps = async () => {
  const data = await fetch(
    `https://api.themoviedb.org/3/movie/popular?api_key=${
      process.env.MOVIES_API
    }&language=en-US&page=${1}`
  ).then((res) => res.json());
  return {
    props: {
      data,
    },
  };
};

export default Home;
